name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  setup:
    uses: .github/workflows/shared-setup.yml
  Tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: Build assets
        run: npm run build

      - name: Run tests with coverage
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

