name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - name: Get shared php setup
        uses: ./.github/actions/php
        with:
          php-version: '8.2'

      - name: Get shared node setup
        uses: ./.github/actions/node
        with:
          node-version: 18

      - name: Build assets
        run: npm run build

      - name: Run tests with coverage
        run: ./bin/phpunit --coverage-clover coverage.xml

