name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0S

      - name: Get shared node setup
        uses: ./.github/actions/node
        with:
          node-version: 18

      - name: Build assets
        run: npm run build

