name: Code Quality

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions: read-all

jobs:
  setup:
    uses: .github/workflows/shared-setup.yml
  CodingStandards:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run php-cs-fixer
        run: composer run-script phpcs

      - name: Run phpstan
        run: composer run-script phpstan

      - name: Run Rector
        run: ./vendor/bin/rector process ./src

      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
