name: Lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions: read-all

jobs:
  setup:
    uses: .github/workflows/shared-setup.yml
  Lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint twig templates
        run: ./bin/console lint:twig templates --env=prod

      - name: Lint yaml config
        run: ./bin/console lint:yaml config --parse-tags

      - name: Validate doctrine schema
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
