name: Security Checks

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: 
      - completed

permissions: read-all

jobs:
  SecurityChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: pcov
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.OS }}-composer-

      - name: Install Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mkdir -p $HOME/bin
          mv /home/runner/.symfony5/bin/symfony $HOME/bin/

      - name: Run Symfony Security Check
        run: $HOME/bin/symfony security:check

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
