name: Security Checks

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

permissions: read-all

jobs:
  setup:
    uses: .github/workflows/shared-setup.yml
  SecurityChecker:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Symfony Security Check
        run: $HOME/bin/symfony check:security

      - name: Check for outdated Composer dependencies
        run: composer outdated --direct --strict
