files:
  ignore:
    - "assets/controllers"
    - "assets/app.js"
    - "assets/app.css"
    - "assets/manifest.json"
    - "assets/bootstrap.js"
    - "assets/controllers.json"
    - "node_modules/**"
    - "vendor/**"
    - "var/**"
    - ".php-cs-fixer.dist.php"
    - ".phpcs.xml"
    - "phpstan.neon"
    - "phpunit.xml.dist"
    - "README.md"
    - "rector.php"
    - "Makefile"
    - "webpack.config.js"
    - "config/bundles.php"
    - "config/preload.php"
    - "public/index.php"
    - "src/Kernel.php"
    - "tests/bootstrap.php"